#language: node_js
#node_js:
# - '0.10'
#before_install:
# - gem install sass
# - gem install foundation
#before_script:
# - npm install -g grunt-cli
# - npm install -g grunt
# - npm install -g bower
# - bower install

# .travis.yml
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php:
        - 5.5
        - 5.6
        - hhvm

before_install:
  - gem install sass
  - gem install foundation
  - npm install -g grunt-cli
  - npm install -g grunt
  - npm install -g bower

before_script:
  - mysql -e 'create database bardiscms;'
  - curl -s http://getcomposer.org/installer | php
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php composer.phar self-update
  - php composer.phar install
  - npm install
  - bower install
  - php app/console cache:clear --env=dev --no-debug --no-warmup
  - php app/console cache:warmup --env=dev --no-debug
  - php app/console cache:clear --env=prod --no-debug --no-warmup
  - php app/console cache:warmup --env=prod --no-debug
  - php app/console doctrine:schema:drop --force
  - php app/console doctrine:schema:create 
  - php app/console doctrine:fixtures:load --append
  - php app/console sonata:media:sync sonata.media.provider.image default
  - php app/console sonata:media:sync sonata.media.provider.image intro
  - php app/console sonata:media:sync sonata.media.provider.image bgimage
  - php app/console sonata:media:sync sonata.media.provider.image icon
  - php app/console assets:install ./web/ --env=prod --no-debug

script:
  - grunt deploy
  - php app/console assetic:dump --env=dev --no-debug
  - php app/console assetic:dump --env=prod --no-debug
  # - mkdir -p build/logs
  # - php vendor/bin/phpunit -c phpunit.xml.dist
  # - phpunit -c app/
#   - phpunit --coverage-text

after_script:
#   - php vendor/bin/coveralls
  # or enable logging
#   - php vendor/bin/coveralls -v