# Starting the routing of the pages based on predefined paths

PageBundle_tagged_noslash:
    path:   /tagged/{extraParams}/{currentpage}/{totalpageitems}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+

PageBundle_tagged_onlypage:
    path:   /tagged/{extraParams}/{currentpage}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+

PageBundle_tagged_onlytag:
    path:   /tagged/{extraParams}
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}

PageBundle_tagged:
    path:   /tagged
    defaults:  { _controller: PageBundle:Default:alias, alias: tagged, extraParams: all, currentpage: 0, totalpageitems: 0}

PageBundle_filtered:
    path:  /filterPages
    defaults: { _controller: PageBundle:Default:filterPages }

PageBundle_sitemap:
    path:  /sitemap.{_format}
    defaults: { _controller: PageBundle:Default:sitemap, _format: xml}
    requirements:
        _format:  xml

PageBundle_sitemapxsl:
    path:  /sitemap.xsl
    defaults: { _controller: PageBundle:Default:sitemapxsl, _format: xml }

# Starting the routing of the pages based on alias
# index is the alias of the homepage (amend if different)

PageBundle_page_noslash:
    path:   /{alias}/{currentpage}/{totalpageitems}/{extraParams}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+
        totalpageitems: \d+

PageBundle_page_only_pagin:
    path:   /{alias}/{currentpage}/{totalpageitems}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}
    requirements:
        currentpage: \d+

PageBundle_page_only_page:
    path:   /{alias}/{currentpage}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}

PageBundle_page:
    path:   /{alias}
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}

PageBundle_index:
    path:   /
    defaults:  { _controller: PageBundle:Default:alias, alias: index, extraParams: all, currentpage: 0, totalpageitems: 0}

#PageBundle_showPage:
#    path:  /showPage/{id}
#    defaults: { _controller: PageBundle:Default:showPage }
#    requirements:
#        id: \d+
