MenuBundle:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

#UserBundle:
#    resource: "@UserBundle/Resources/config/routing.yml"
#    prefix:   /user

# app/config/routing.yml
sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
 
fos_user_register_campaign:
    pattern: /register/track/{campaign}
    defaults:  { _controller: FOSUserBundle:Registration:register }
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
sonata_user_impersonating:
    pattern: /admin/dashboard
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

CommentBundle:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /

BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

PageBundle:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /