parameters:
#    blog.example.class: BardisCMS\BlogBundle\Example

services:

  blog.form.filterblogpostsform:
    class: BardisCMS\BlogBundle\Form\Type\FilterBlogPostsFormType
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: form.type, alias: filterblogpostsform }
